# Generated by Django 3.1.4 on 2020-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201228_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, default='Bottom Text', null=True),
        ),
    ]
